apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tap-flask
  description: A sample catalog for Backstage
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./tap-flask.yaml
