apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-flask.dev.itq.lab.20240323122639.0.0+build.533fea2
spec:
  refName: tap-flask.dev.itq.lab
  version: 20240323122639.0.0+build.533fea2
  releaseNotes: |
    Release v20240323122639.0.0+build.533fea2 of package tap-flask.dev.itq.lab
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.tap.itq.lab/tap/workloads/tap-flask-dev-bundle@sha256:de44b9857b948548a9b115a31d47cc475fd37ad5ea0817a52c09144549c20a2a
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

