apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-flask.dev.itq.lab.20240323122349.0.0+build.855e655
spec:
  refName: tap-flask.dev.itq.lab
  version: 20240323122349.0.0+build.855e655
  releaseNotes: |
    Release v20240323122349.0.0+build.855e655 of package tap-flask.dev.itq.lab
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.tap.itq.lab/tap/workloads/tap-flask-dev-bundle@sha256:5eea82eda4b2b4ecde3b617fa69ea0ca0f9c504080fafb462eabdf2b89c92619
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

