apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-flask.dev.itq.lab.20240323121755.0.0+build.47e4e0d
spec:
  refName: tap-flask.dev.itq.lab
  version: 20240323121755.0.0+build.47e4e0d
  releaseNotes: |
    Release v20240323121755.0.0+build.47e4e0d of package tap-flask.dev.itq.lab
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.tap.itq.lab/tap/workloads/tap-flask-dev-bundle@sha256:8e97d6c7f5f06430a26d3aec57277c19d11d54cf4b880f2dc1021021326efe36
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

