apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-flask.dev.itq.lab.20240323122945.0.0+build.66fdd14
spec:
  refName: tap-flask.dev.itq.lab
  version: 20240323122945.0.0+build.66fdd14
  releaseNotes: |
    Release v20240323122945.0.0+build.66fdd14 of package tap-flask.dev.itq.lab
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.tap.itq.lab/tap/workloads/tap-flask-dev-bundle@sha256:c38747ef6fc7a7eb3f1b2a929c12503ef3ff1b5ce2559102af02bca4530dd94c
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

