apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-flask.dev.itq.lab.20240323120556.0.0+build.e8d2733
spec:
  refName: tap-flask.dev.itq.lab
  version: 20240323120556.0.0+build.e8d2733
  releaseNotes: |
    Release v20240323120556.0.0+build.e8d2733 of package tap-flask.dev.itq.lab
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.tap.itq.lab/tap/workloads/tap-flask-dev-bundle@sha256:3bffe862fed474e269bff0d937e24143dfcfb98d12015f058ee36f215f536e26
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

