apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-flask.dev.itq.lab.20240323124559.0.0+build.5e3bd63
spec:
  refName: tap-flask.dev.itq.lab
  version: 20240323124559.0.0+build.5e3bd63
  releaseNotes: |
    Release v20240323124559.0.0+build.5e3bd63 of package tap-flask.dev.itq.lab
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.tap.itq.lab/tap/workloads/tap-flask-dev-bundle@sha256:3c752e5af0b2f8c7047420c1a295c0bae62474c8f189f72041ecfbcba1e0a20a
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

