apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-flask.dev.itq.lab.20240323123452.0.0+build.34f60f0
spec:
  refName: tap-flask.dev.itq.lab
  version: 20240323123452.0.0+build.34f60f0
  releaseNotes: |
    Release v20240323123452.0.0+build.34f60f0 of package tap-flask.dev.itq.lab
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.tap.itq.lab/tap/workloads/tap-flask-dev-bundle@sha256:c5d5edf96c7b3a88ae444467c6a3ce04b2b0e608c2ee16d678c085f45fd40450
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

