apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-flask.dev.itq.lab.20240323120259.0.0+build.427931c
spec:
  refName: tap-flask.dev.itq.lab
  version: 20240323120259.0.0+build.427931c
  releaseNotes: |
    Release v20240323120259.0.0+build.427931c of package tap-flask.dev.itq.lab
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.tap.itq.lab/tap/workloads/tap-flask-dev-bundle@sha256:ffd72cd08d55c9467569f9cb622ae32fe69652fdd21da287217acf08a5c91809
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

