apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-flask.dev.itq.lab.20240323122855.0.0+build.f10cdc8
spec:
  refName: tap-flask.dev.itq.lab
  version: 20240323122855.0.0+build.f10cdc8
  releaseNotes: |
    Release v20240323122855.0.0+build.f10cdc8 of package tap-flask.dev.itq.lab
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.tap.itq.lab/tap/workloads/tap-flask-dev-bundle@sha256:69961308e6c2c5d9a0acdbd913cfe7a64cbb0d5ec78e26e3abfe9c85c31cab76
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

