apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-flask.dev.itq.lab.20240323123145.0.0+build.e6a6867
spec:
  refName: tap-flask.dev.itq.lab
  version: 20240323123145.0.0+build.e6a6867
  releaseNotes: |
    Release v20240323123145.0.0+build.e6a6867 of package tap-flask.dev.itq.lab
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.tap.itq.lab/tap/workloads/tap-flask-dev-bundle@sha256:2e7cd3010ec4ffdb25ce63164f7ceb6504d08332331d4b6f2bcfae53a33db5b8
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

