apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-flask.dev.itq.lab.20240323123755.0.0+build.049370d
spec:
  refName: tap-flask.dev.itq.lab
  version: 20240323123755.0.0+build.049370d
  releaseNotes: |
    Release v20240323123755.0.0+build.049370d of package tap-flask.dev.itq.lab
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.tap.itq.lab/tap/workloads/tap-flask-dev-bundle@sha256:b906fbc0ac679bd46506503a8392db4dc29081140026c1653e909b734e53bce6
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

